language: ruby
sudo: false
bundler_args: --without development
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - "CHECK=spec SPEC_OPTS='--color --format documentation'"
  - "CHECK=rubocop"

matrix:
  fast_finish: true
