language: ruby
sudo: false
bundler_args: --without development
script:
  - "bundle exec $CHECK"
notifications:
  email: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

env:
  - "CHECK=rspec spec -c -fd spec/unit"

matrix:
  fast_finish: true
